name: Build & Test API

on:
  push:
    paths:
      - "apps/api/**"
  pull_request:
    paths:
      - "apps/api/**"

jobs:
  api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies at root
        run: pnpm install

      - name: Build API
        run: pnpm --filter api build

      - name: Test API
        run: pnpm --filter api test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
